# docker-compose.yml

version: '3.8'

services:
  indexer:
    build: .
    container_name: rated-log-indexer
    environment:
      - PYTHONPATH=/indexer/src
    volumes:
      - .:/indexer
    command: ["python", "src/main.py"]
