name: CI

permissions:
  id-token: write
  contents: read

on:
  pull_request:


jobs:
  test:
    name: Test / Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build docker images
      run: docker compose build

    - name: Run Black
      run: docker compose run --rm -T --entrypoint black indexer --check .

    - name: Run MyPy
      run: docker compose run --rm -T --entrypoint mypy indexer --check .

    - name: Run Ruff
      run: docker compose run --rm -T --entrypoint ruff indexer check .

    - name: Run unit tests
      run: docker compose run --rm -T --entrypoint pytest test tests/ -v
